### ISSUE TITLE
[bug] settings `markiscodecoverage.searchCriteria` change, but output not changed

### ISSUE THREAD

**Issue by loynoir** [markis/vscode-code-coverage#90]
### Description
settings `markiscodecoverage.searchCriteria` change, but output not changed.

### Reproduce: 1
1. Change `markiscodecoverage.searchCriteria`
2. ctrl+shift+p show code coverage

Expected: output using new lcov path

Actual: output using **old** lcov path

### Reproduce: 2
1. Change `markiscodecoverage.searchCriteria`
2. ctrl+shift+p hide code coverage
3. ctrl+shift+p show code coverage

Expected: output using new lcov path

Actual: output using **old** lcov path

### Workaround
1. Change `markiscodecoverage.searchCriteria`
2. ctrl+shift+p reload window
3. ctrl+shift+p show code coverage

Actual: output using new lcov path

**Comment by m-flak** [comment]
@loynoir Your issue should be fixed. Would you like to test it out on your end?

**Comment by loynoir** [comment]
Before

```json
"markiscodecoverage.searchCriteria": "build/coverage-reproduce/v1/lcov.info",
```

After

```json
"markiscodecoverage.searchCriteria": "build/coverage-reproduce/v2/lcov.info",
```

Reproduce

-  `hide code coverage`
-  `show code coverage`

However

- `markis.code-coverage-1.10.1` still show v1 coverage.
- After `reload window`, `markis.code-coverage-1.10.1` show v2 coverage.

So, 

- Is it merged?

- If not, could you provide a patch for dir `extensions/markis.code-coverage-1.10.1/`?

**Comment by markis** [comment]
@loynoir, I just published 1.11.0, which has the [changes](https://github.com/markis/vscode-code-coverage/pull/101) from @m-flak.  You should be able to update and try again.

**Comment by loynoir** [comment]
Verified working. :)
